# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1343, 896)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/2019bhkj/.designer/backup/data/picture/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 10, 501, 801))
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_8.setGeometry(QtCore.QRect(190, 280, 82, 24))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_25.addWidget(self.label_43)
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_25.addWidget(self.comboBox_12)
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_9.setGeometry(QtCore.QRect(370, 280, 84, 24))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_26.addWidget(self.label_45)
        self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget_9)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_26.addWidget(self.comboBox_13)
        self.line_5 = QtWidgets.QFrame(self.groupBox_9)
        self.line_5.setGeometry(QtCore.QRect(10, 170, 461, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.groupBox_9)
        self.line_6.setGeometry(QtCore.QRect(10, 340, 461, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.layoutWidget_14 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_14.setGeometry(QtCore.QRect(20, 50, 174, 24))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_12.addWidget(self.label_52)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_12.addWidget(self.lineEdit_17)
        self.layoutWidget_15 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_15.setGeometry(QtCore.QRect(240, 50, 80, 24))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_31.addWidget(self.label_53)
        self.comboBox_16 = QtWidgets.QComboBox(self.layoutWidget_15)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.horizontalLayout_31.addWidget(self.comboBox_16)
        self.layoutWidget_16 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_16.setGeometry(QtCore.QRect(370, 50, 88, 24))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_16)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_32.addWidget(self.label_54)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget_16)
        self.spinBox_4.setMaximum(86)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_32.addWidget(self.spinBox_4)
        self.layoutWidget_17 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_17.setGeometry(QtCore.QRect(20, 110, 174, 24))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_33.addWidget(self.label_55)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_17)
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_33.addWidget(self.lineEdit_18)
        self.layoutWidget_18 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_18.setGeometry(QtCore.QRect(240, 110, 221, 24))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.layoutWidget_18)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_18)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_34.addWidget(self.label_56)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_34.addWidget(self.lineEdit_19)
        self.layoutWidget_19 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_19.setGeometry(QtCore.QRect(20, 210, 171, 24))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget_19)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_57 = QtWidgets.QLabel(self.layoutWidget_19)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_35.addWidget(self.label_57)
        self.comboBox_17 = QtWidgets.QComboBox(self.layoutWidget_19)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.horizontalLayout_35.addWidget(self.comboBox_17)
        self.layoutWidget_20 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_20.setGeometry(QtCore.QRect(20, 280, 82, 24))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.layoutWidget_20)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_20)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_36.addWidget(self.label_58)
        self.comboBox_18 = QtWidgets.QComboBox(self.layoutWidget_20)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.horizontalLayout_36.addWidget(self.comboBox_18)
        self.layoutWidget_21 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_21.setGeometry(QtCore.QRect(20, 380, 121, 24))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.layoutWidget_21)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_21)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_37.addWidget(self.label_59)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget_21)
        self.spinBox_5.setMaximum(60)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_37.addWidget(self.spinBox_5)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 570, 461, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_61 = QtWidgets.QLabel(self.layoutWidget)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_27.addWidget(self.label_61)
        self.comboBox_20 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.horizontalLayout_27.addWidget(self.comboBox_20)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_27)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_28.addWidget(self.label_47)
        self.comboBox_21 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.horizontalLayout_28.addWidget(self.comboBox_21)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_28)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem2)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_49 = QtWidgets.QLabel(self.layoutWidget)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_38.addWidget(self.label_49)
        self.comboBox_22 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.horizontalLayout_38.addWidget(self.comboBox_22)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_38)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 470, 301, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_29.addWidget(self.label_50)
        self.comboBox_14 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_29.addWidget(self.comboBox_14)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_29)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem3)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_30.addWidget(self.label_51)
        self.comboBox_15 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.horizontalLayout_30.addWidget(self.comboBox_15)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_30)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget2.setGeometry(QtCore.QRect(261, 210, 160, 21))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_45.addWidget(self.label_62)
        self.comboBox_19 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.horizontalLayout_45.addWidget(self.comboBox_19)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(550, 10, 761, 801))
        self.groupBox_10.setObjectName("groupBox_10")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 50, 451, 371))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 430, 451, 371))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.label_63 = QtWidgets.QLabel(self.groupBox_10)
        self.label_63.setGeometry(QtCore.QRect(20, 60, 431, 351))
        self.label_63.setText("")
        self.label_63.setObjectName("label_63")
        self.layoutWidget_23 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_23.setGeometry(QtCore.QRect(620, 20, 116, 26))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.layoutWidget_23)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_23)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_39.addWidget(self.label_64)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget_23)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_39.addWidget(self.pushButton_16)
        self.layoutWidget_24 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_24.setGeometry(QtCore.QRect(470, 50, 261, 24))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.layoutWidget_24)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_24)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_40.addWidget(self.label_65)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_24)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_40.addWidget(self.lineEdit_21)
        self.layoutWidget_25 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_25.setGeometry(QtCore.QRect(470, 430, 261, 24))
        self.layoutWidget_25.setObjectName("layoutWidget_25")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.layoutWidget_25)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_25)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_41.addWidget(self.label_66)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_25)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_41.addWidget(self.lineEdit_22)
        self.label_67 = QtWidgets.QLabel(self.groupBox_10)
        self.label_67.setGeometry(QtCore.QRect(20, 440, 431, 351))
        self.label_67.setText("")
        self.label_67.setObjectName("label_67")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 10, 501, 801))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 280, 82, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_8)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(370, 280, 84, 24))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_9)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 610, 421, 48))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_18.addWidget(self.label_34)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_18.addWidget(self.lineEdit_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 690, 421, 48))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_3.addWidget(self.label_35)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_19.addWidget(self.label_36)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_19.addWidget(self.lineEdit_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 440, 132, 24))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_20.addWidget(self.label_37)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget_6)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_10)
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(230, 440, 132, 24))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_21.addWidget(self.label_38)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget_7)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_11)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setGeometry(QtCore.QRect(10, 170, 461, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.groupBox_4)
        self.line_4.setGeometry(QtCore.QRect(10, 340, 461, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 50, 174, 24))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(240, 50, 80, 24))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(370, 50, 88, 24))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget5)
        self.spinBox_2.setMaximum(86)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_10.addWidget(self.spinBox_2)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 110, 174, 24))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_7.addWidget(self.label_21)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(240, 110, 221, 24))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_8.addWidget(self.lineEdit_7)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget8.setGeometry(QtCore.QRect(20, 210, 171, 24))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget8)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_2)
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget9.setGeometry(QtCore.QRect(20, 280, 82, 24))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_7)
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget10.setGeometry(QtCore.QRect(20, 380, 121, 24))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_16.addWidget(self.label_30)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget10)
        self.spinBox_3.setMaximum(60)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_16.addWidget(self.spinBox_3)
        self.layoutWidget11 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget11.setGeometry(QtCore.QRect(20, 510, 421, 48))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_32.setObjectName("label_32")
        self.verticalLayout.addWidget(self.label_32)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_17.addWidget(self.label_31)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_17.addWidget(self.lineEdit_8)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.layoutWidget12 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget12.setGeometry(QtCore.QRect(261, 210, 160, 21))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_44.addWidget(self.label_26)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget12)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_44.addWidget(self.comboBox_3)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(550, 10, 761, 801))
        self.groupBox_8.setObjectName("groupBox_8")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 50, 451, 371))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 430, 451, 371))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.label_40 = QtWidgets.QLabel(self.groupBox_8)
        self.label_40.setGeometry(QtCore.QRect(20, 60, 431, 351))
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.layoutWidget13 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget13.setGeometry(QtCore.QRect(620, 20, 116, 26))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_22.addWidget(self.label_39)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget13)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_22.addWidget(self.pushButton_15)
        self.layoutWidget14 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget14.setGeometry(QtCore.QRect(470, 50, 261, 24))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget14)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_23.addWidget(self.label_42)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget14)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_23.addWidget(self.lineEdit_13)
        self.layoutWidget15 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget15.setGeometry(QtCore.QRect(470, 430, 261, 24))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget15)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_24.addWidget(self.label_44)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget15)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_24.addWidget(self.lineEdit_14)
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setGeometry(QtCore.QRect(20, 440, 431, 351))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "唾液腺癌智能辅助医疗软件"))
        self.pushButton_3.setText(_translate("Form", "退出"))
        self.groupBox_9.setTitle(_translate("Form", "新患者信息录入模块"))
        self.label_43.setText(_translate("Form", "N分期："))
        self.comboBox_12.setItemText(0, _translate("Form", "0"))
        self.comboBox_12.setItemText(1, _translate("Form", "1"))
        self.comboBox_12.setItemText(2, _translate("Form", "2"))
        self.comboBox_12.setItemText(3, _translate("Form", "3"))
        self.label_45.setText(_translate("Form", "M分期："))
        self.comboBox_13.setItemText(0, _translate("Form", "0"))
        self.comboBox_13.setItemText(1, _translate("Form", "1"))
        self.label_52.setText(_translate("Form", "姓名："))
        self.label_53.setText(_translate("Form", "性别："))
        self.comboBox_16.setItemText(0, _translate("Form", "男"))
        self.comboBox_16.setItemText(1, _translate("Form", "女"))
        self.label_54.setText(_translate("Form", "年龄："))
        self.label_55.setText(_translate("Form", "电话："))
        self.label_56.setText(_translate("Form", "住址："))
        self.label_57.setText(_translate("Form", "发病部位："))
        self.comboBox_17.setItemText(0, _translate("Form", "腮腺"))
        self.comboBox_17.setItemText(1, _translate("Form", "颌下腺"))
        self.comboBox_17.setItemText(2, _translate("Form", "舌下腺+口底"))
        self.comboBox_17.setItemText(3, _translate("Form", "颚"))
        self.comboBox_17.setItemText(4, _translate("Form", "磨牙后区"))
        self.comboBox_17.setItemText(5, _translate("Form", "颊"))
        self.comboBox_17.setItemText(6, _translate("Form", "舌"))
        self.comboBox_17.setItemText(7, _translate("Form", "唇"))
        self.comboBox_17.setItemText(8, _translate("Form", "上颌"))
        self.comboBox_17.setItemText(9, _translate("Form", "其他"))
        self.label_58.setText(_translate("Form", "T分期："))
        self.comboBox_18.setItemText(0, _translate("Form", "1"))
        self.comboBox_18.setItemText(1, _translate("Form", "2"))
        self.comboBox_18.setItemText(2, _translate("Form", "3"))
        self.comboBox_18.setItemText(3, _translate("Form", "4"))
        self.label_59.setText(_translate("Form", "预测时间："))
        self.label_61.setText(_translate("Form", "局部复发："))
        self.comboBox_20.setItemText(0, _translate("Form", "否"))
        self.comboBox_20.setItemText(1, _translate("Form", "是"))
        self.label_47.setText(_translate("Form", "颈部复发："))
        self.comboBox_21.setItemText(0, _translate("Form", "否"))
        self.comboBox_21.setItemText(1, _translate("Form", "是"))
        self.label_49.setText(_translate("Form", "远处转移："))
        self.comboBox_22.setItemText(0, _translate("Form", "否"))
        self.comboBox_22.setItemText(1, _translate("Form", "是"))
        self.label_50.setText(_translate("Form", "放疗或粒子："))
        self.comboBox_14.setItemText(0, _translate("Form", "否"))
        self.comboBox_14.setItemText(1, _translate("Form", "是"))
        self.comboBox_14.setItemText(2, _translate("Form", "未知"))
        self.label_51.setText(_translate("Form", "化疗："))
        self.comboBox_15.setItemText(0, _translate("Form", "否"))
        self.comboBox_15.setItemText(1, _translate("Form", "是"))
        self.comboBox_15.setItemText(2, _translate("Form", "未知"))
        self.label_62.setText(_translate("Form", "病理类型："))
        self.comboBox_19.setItemText(0, _translate("Form", "高分化粘表"))
        self.comboBox_19.setItemText(1, _translate("Form", "中分化粘表"))
        self.comboBox_19.setItemText(2, _translate("Form", "低分化粘表"))
        self.comboBox_19.setItemText(3, _translate("Form", "腺样囊性癌"))
        self.comboBox_19.setItemText(4, _translate("Form", "癌在多形性腺瘤中"))
        self.comboBox_19.setItemText(5, _translate("Form", "非特异性腺癌"))
        self.comboBox_19.setItemText(6, _translate("Form", "腺泡细胞癌"))
        self.comboBox_19.setItemText(7, _translate("Form", "肌上皮癌"))
        self.comboBox_19.setItemText(8, _translate("Form", "多型性腺癌"))
        self.comboBox_19.setItemText(9, _translate("Form", "基底细胞腺癌"))
        self.comboBox_19.setItemText(10, _translate("Form", "唾液腺导管癌"))
        self.comboBox_19.setItemText(11, _translate("Form", "鳞状细胞癌"))
        self.comboBox_19.setItemText(12, _translate("Form", "淋巴上皮癌"))
        self.comboBox_19.setItemText(13, _translate("Form", "上皮-肌上皮癌"))
        self.comboBox_19.setItemText(14, _translate("Form", "嗜酸细胞腺癌"))
        self.comboBox_19.setItemText(15, _translate("Form", "透明细胞癌"))
        self.comboBox_19.setItemText(16, _translate("Form", "其他"))
        self.groupBox_10.setTitle(_translate("Form", "智能辅助诊断模块"))
        self.label_64.setText(_translate("Form", "诊断："))
        self.pushButton_16.setText(_translate("Form", "开始"))
        self.label_65.setText(_translate("Form", "生存概率："))
        self.label_66.setText(_translate("Form", "5年概率："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "新患者病情预测"))
        self.groupBox_4.setTitle(_translate("Form", "患者信息录入模块"))
        self.label_28.setText(_translate("Form", "N分期："))
        self.comboBox_8.setItemText(0, _translate("Form", "0"))
        self.comboBox_8.setItemText(1, _translate("Form", "1"))
        self.comboBox_8.setItemText(2, _translate("Form", "2"))
        self.comboBox_8.setItemText(3, _translate("Form", "3"))
        self.label_29.setText(_translate("Form", "M分期："))
        self.comboBox_9.setItemText(0, _translate("Form", "0"))
        self.comboBox_9.setItemText(1, _translate("Form", "1"))
        self.label_33.setText(_translate("Form", "注：若无复发填-否，有复发填具体复发月份，例如-3。"))
        self.label_34.setText(_translate("Form", "颈部复发："))
        self.label_35.setText(_translate("Form", "注：若无远处转移填-否，有远处转移填具体转移时月份，例如-3。"))
        self.label_36.setText(_translate("Form", "远处转移："))
        self.label_37.setText(_translate("Form", "放疗或粒子："))
        self.comboBox_10.setItemText(0, _translate("Form", "否"))
        self.comboBox_10.setItemText(1, _translate("Form", "是"))
        self.comboBox_10.setItemText(2, _translate("Form", "未知"))
        self.label_38.setText(_translate("Form", "化疗："))
        self.comboBox_11.setItemText(0, _translate("Form", "否"))
        self.comboBox_11.setItemText(1, _translate("Form", "是"))
        self.comboBox_11.setItemText(2, _translate("Form", "未知"))
        self.label_20.setText(_translate("Form", "姓名："))
        self.label_23.setText(_translate("Form", "性别："))
        self.comboBox.setItemText(0, _translate("Form", "男"))
        self.comboBox.setItemText(1, _translate("Form", "女"))
        self.label_24.setText(_translate("Form", "年龄："))
        self.label_21.setText(_translate("Form", "电话："))
        self.label_22.setText(_translate("Form", "住址："))
        self.label_25.setText(_translate("Form", "发病部位："))
        self.comboBox_2.setItemText(0, _translate("Form", "腮腺"))
        self.comboBox_2.setItemText(1, _translate("Form", "颌下腺"))
        self.comboBox_2.setItemText(2, _translate("Form", "舌下腺+口底"))
        self.comboBox_2.setItemText(3, _translate("Form", "颚"))
        self.comboBox_2.setItemText(4, _translate("Form", "磨牙后区"))
        self.comboBox_2.setItemText(5, _translate("Form", "颊"))
        self.comboBox_2.setItemText(6, _translate("Form", "舌"))
        self.comboBox_2.setItemText(7, _translate("Form", "唇"))
        self.comboBox_2.setItemText(8, _translate("Form", "上颌"))
        self.comboBox_2.setItemText(9, _translate("Form", "其他"))
        self.label_27.setText(_translate("Form", "T分期："))
        self.comboBox_7.setItemText(0, _translate("Form", "1"))
        self.comboBox_7.setItemText(1, _translate("Form", "2"))
        self.comboBox_7.setItemText(2, _translate("Form", "3"))
        self.comboBox_7.setItemText(3, _translate("Form", "4"))
        self.label_30.setText(_translate("Form", "随访时间："))
        self.label_32.setText(_translate("Form", "注：若无复发填-否，有复发填具体复发月份，例如-3。"))
        self.label_31.setText(_translate("Form", "局部复发："))
        self.label_26.setText(_translate("Form", "病理类型："))
        self.comboBox_3.setItemText(0, _translate("Form", "高分化粘表"))
        self.comboBox_3.setItemText(1, _translate("Form", "中分化粘表"))
        self.comboBox_3.setItemText(2, _translate("Form", "低分化粘表"))
        self.comboBox_3.setItemText(3, _translate("Form", "腺样囊性癌"))
        self.comboBox_3.setItemText(4, _translate("Form", "癌在多形性腺瘤中"))
        self.comboBox_3.setItemText(5, _translate("Form", "非特异性腺癌"))
        self.comboBox_3.setItemText(6, _translate("Form", "腺泡细胞癌"))
        self.comboBox_3.setItemText(7, _translate("Form", "肌上皮癌"))
        self.comboBox_3.setItemText(8, _translate("Form", "多型性腺癌"))
        self.comboBox_3.setItemText(9, _translate("Form", "基底细胞腺癌"))
        self.comboBox_3.setItemText(10, _translate("Form", "唾液腺导管癌"))
        self.comboBox_3.setItemText(11, _translate("Form", "鳞状细胞癌"))
        self.comboBox_3.setItemText(12, _translate("Form", "淋巴上皮癌"))
        self.comboBox_3.setItemText(13, _translate("Form", "上皮-肌上皮癌"))
        self.comboBox_3.setItemText(14, _translate("Form", "嗜酸细胞腺癌"))
        self.comboBox_3.setItemText(15, _translate("Form", "透明细胞癌"))
        self.comboBox_3.setItemText(16, _translate("Form", "其他"))
        self.groupBox_8.setTitle(_translate("Form", "智能辅助诊断模块"))
        self.label_39.setText(_translate("Form", "诊断："))
        self.pushButton_15.setText(_translate("Form", "开始"))
        self.label_42.setText(_translate("Form", "生存概率："))
        self.label_44.setText(_translate("Form", "5年概率："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "患者病情诊断"))

